name: Build and Release
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, deploy
      run: |
        yarn install
        yarn run deploy:production
    - name: Release build
      uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SRC_FOLDER: dist
        DEST_OWNER: max-greive-latori
        DEST_REPO: watcher
        DEST_BRANCH: main
